### ISSUE TITLE
Styling for text enclosed in `` fix

### ISSUE THREAD

**Issue by rossoskull** [rossoskull/blog#8]
Improve the styling for the texts enclosed in ``.

**Screenshot for the bug**
![screenshot from 2018-10-03 23-50-36](https://user-images.githubusercontent.com/27884543/46430672-62538600-c767-11e8-8752-d6edda9dc993.png)

Here the part 'rossoskull.me' should have a lighter background.

Visit here : http://rossoskull.me/learn/coding/2018/08/31/blog-init.html

**Comment by sdhutchins** [comment]
I was just about to ping you. I noticed this today. I can handle that. It's just the syntax highlighting looks different with the white background.

**Comment by rossoskull** [comment]
Should I assign you then?

**Comment by sdhutchins** [comment]
Yeah, I can change that quickly.

**Comment by logichub** [comment]
Which one is looking better?
1. Current highlight background with white font color
```
.highlighter-rouge {
    background-color: #424242;
    color: #fff;
}
```

![image](https://user-images.githubusercontent.com/6245858/46433578-ad22cd00-c76a-11e8-851a-86605aeac8aa.png)

2. A bit lighter highlight background color with white font color:
```
.highlighter-rouge {
    background-color: rgba(25, 49, 73, 0.6);
    color: #fff;
}
```

![image](https://user-images.githubusercontent.com/6245858/46433653-d9d6e480-c76a-11e8-957a-d2ba1876994c.png)
